// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TS.Infrastructure.Persistence;

#nullable disable

namespace TS.Infrastructure.Migrations
{
    [DbContext(typeof(TSDbContext))]
    [Migration("20261008085215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_revoked");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiration", "expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_refresh_tokens_hash_length", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("TS.Domain.Entities.ShareAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ShareLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_link_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("was_successful");

                    b.HasKey("Id");

                    b.HasIndex("AccessedAtUtc")
                        .HasDatabaseName("ix_share_access_logs_accessed_at");

                    b.HasIndex("UserId");

                    b.HasIndex("ShareLinkId", "AccessedAtUtc")
                        .HasDatabaseName("ix_share_access_logs_link_time");

                    b.ToTable("share_access_logs", (string)null);
                });

            modelBuilder.Entity("TS.Domain.Entities.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at_utc");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("TextSnippetId")
                        .HasColumnType("uuid")
                        .HasColumnName("text_snippet_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<short>("TokenKeyVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("token_key_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("use_count");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_share_links_expires_at");

                    b.HasIndex("TextSnippetId")
                        .HasDatabaseName("ix_share_links_text_snippet_id");

                    b.HasIndex("TokenKeyVersion", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_share_links_token");

                    b.ToTable("share_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_share_links_expiration", "expires_at_utc IS NULL OR expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_share_links_key_version", "token_key_version > 0");

                            t.HasCheckConstraint("ck_share_links_max_uses", "max_uses IS NULL OR max_uses > 0");

                            t.HasCheckConstraint("ck_share_links_token_hash_length", "octet_length(token_hash) = 32");

                            t.HasCheckConstraint("ck_share_links_use_count", "use_count >= 0");

                            t.HasCheckConstraint("ck_share_links_use_limit", "max_uses IS NULL OR use_count <= max_uses");
                        });
                });

            modelBuilder.Entity("TS.Domain.Entities.TextSnippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("LastViewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at_utc");

                    b.Property<int?>("MaxViews")
                        .HasColumnType("integer")
                        .HasColumnName("max_views");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_text_snippets_expires_at");

                    b.HasIndex("OwnerUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_text_snippets_owner_created");

                    b.ToTable("text_snippets", null, t =>
                        {
                            t.HasCheckConstraint("ck_text_snippets_content_length", "octet_length(content) <= 1048576");

                            t.HasCheckConstraint("ck_text_snippets_expiration", "expires_at_utc IS NULL OR expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_text_snippets_max_views", "max_views IS NULL OR max_views > 0");

                            t.HasCheckConstraint("ck_text_snippets_view_count", "view_count >= 0");

                            t.HasCheckConstraint("ck_text_snippets_view_limit", "max_views IS NULL OR view_count <= max_views");
                        });
                });

            modelBuilder.Entity("TS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TS.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TS.Domain.Entities.ShareAccessLog", b =>
                {
                    b.HasOne("TS.Domain.Entities.ShareLink", "ShareLink")
                        .WithMany("AccessLogs")
                        .HasForeignKey("ShareLinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TS.Domain.Entities.User", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ShareLink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TS.Domain.Entities.ShareLink", b =>
                {
                    b.HasOne("TS.Domain.Entities.TextSnippet", "TextSnippet")
                        .WithMany("ShareLinks")
                        .HasForeignKey("TextSnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TextSnippet");
                });

            modelBuilder.Entity("TS.Domain.Entities.TextSnippet", b =>
                {
                    b.HasOne("TS.Domain.Entities.User", "Owner")
                        .WithMany("Snippets")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TS.Domain.Entities.ShareLink", b =>
                {
                    b.Navigation("AccessLogs");
                });

            modelBuilder.Entity("TS.Domain.Entities.TextSnippet", b =>
                {
                    b.Navigation("ShareLinks");
                });

            modelBuilder.Entity("TS.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Snippets");
                });
#pragma warning restore 612, 618
        }
    }
}
